// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0U1-pYH0Vw66IDUgK4q37p8I0TbVlolM',
    appId: '1:722415507675:web:b27027d17e52f1ac7014fe',
    messagingSenderId: '722415507675',
    projectId: 'lab-assignment-70850',
    authDomain: 'lab-assignment-70850.firebaseapp.com',
    storageBucket: 'lab-assignment-70850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzTc-5r4HbsNE_4ZbFFxGDs2c5TqHl0Q',
    appId: '1:722415507675:android:ffe5a1182259b0b27014fe',
    messagingSenderId: '722415507675',
    projectId: 'lab-assignment-70850',
    storageBucket: 'lab-assignment-70850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEmmfYWKptJol9GLm8Bw3HXWDF92-tB0s',
    appId: '1:722415507675:ios:31f105a5bfd5abce7014fe',
    messagingSenderId: '722415507675',
    projectId: 'lab-assignment-70850',
    storageBucket: 'lab-assignment-70850.appspot.com',
    iosBundleId: 'com.noman.lab8.lab8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0U1-pYH0Vw66IDUgK4q37p8I0TbVlolM',
    appId: '1:722415507675:web:8c271f8a649951df7014fe',
    messagingSenderId: '722415507675',
    projectId: 'lab-assignment-70850',
    authDomain: 'lab-assignment-70850.firebaseapp.com',
    storageBucket: 'lab-assignment-70850.appspot.com',
  );
}
